"""Version, validate, and migrate human-readable definitions stores."""

from __future__ import annotations

import fcntl
import hashlib
import os
import shutil
import stat
import tempfile
import uuid
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterator

import yaml

from nro.engine.io import atomic_write_text, sync_directory

MANIFEST = ".nro-definitions.yml"
LOCK = ".nro-definitions.lock"
RECOVERY = ".nro-definitions-recovery"
MANAGED_CATEGORIES = (
    "site",
    "configs",
    "workflows",
    "models",
    "events",
    "markup",
    "hardware",
    "bidsify",
    "scanplans",
)
MANAGED_NOTICE = (
    "# Managed by nro. Do not edit this file directly.\n"
    "# Use `nro create`, `nro edit`, `nro delete`, or `nro definitions`.\n"
)


@dataclass(frozen=True)
class Migration:
    """One ordered definitions-store schema transformation."""

    source: int
    destination: int
    release: str
    apply: Callable[[Path], None]


def _managed_paths(root: Path) -> tuple[Path, ...]:
    paths: list[Path] = []
    for category in MANAGED_CATEGORIES:
        directory = root / category
        if not directory.is_dir():
            continue
        for parent, directories, names in os.walk(directory, followlinks=False):
            directories[:] = [
                name for name in directories if not name.startswith(".") and name != "__pycache__"
            ]
            for name in names:
                if name.startswith(".") or name.endswith((".pyc", ".pyo")):
                    continue
                path = Path(parent) / name
                if path.is_file() and not path.is_symlink():
                    paths.append(path)
    return tuple(sorted(paths))


def _digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _reject_symlinks(root: Path) -> None:
    for category in MANAGED_CATEGORIES:
        directory = root / category
        if directory.is_symlink():
            raise ValueError(f"Definition directories must not be symlinks: {directory}")
        if not directory.is_dir():
            continue
        for parent, directories, names in os.walk(directory, followlinks=False):
            for name in (*directories, *names):
                path = Path(parent) / name
                if path.is_symlink():
                    raise ValueError(f"Definitions must not be symlinks: {path}")


def _manifest_document(root: Path, version: int) -> dict[str, object]:
    return {
        "schema_version": version,
        "files": {str(path.relative_to(root)): _digest(path) for path in _managed_paths(root)},
    }


def _manifest_text(root: Path, version: int) -> str:
    return MANAGED_NOTICE + yaml.safe_dump(_manifest_document(root, version), sort_keys=False)


def _read_manifest(root: Path) -> dict[str, object] | None:
    path = root / MANIFEST
    if not path.is_file():
        return None
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if (
        not isinstance(value, dict)
        or set(value) != {"schema_version", "files"}
        or not isinstance(value["schema_version"], int)
        or not isinstance(value["files"], dict)
        or any(
            not isinstance(key, str) or not isinstance(item, str)
            for key, item in value["files"].items()
        )
    ):
        raise ValueError(f"Invalid definitions-store manifest: {path}")
    return value


def store_schema(root: Path) -> int:
    """Return the declared schema, using zero for an unversioned legacy store."""
    manifest = _read_manifest(Path(root))
    return 0 if manifest is None else int(manifest["schema_version"])


def validate_store_integrity(root: Path, *, expected: int | None = None) -> None:
    """Reject an unversioned, unsupported, or directly modified store."""
    root = Path(root)
    manifest = _read_manifest(root)
    if manifest is None:
        raise ValueError(
            f"Definitions store is unversioned: {root}; rerun installation maintenance"
        )
    _reject_symlinks(root)
    target = SCHEMA_VERSION if expected is None else expected
    version = int(manifest["schema_version"])
    if version != target:
        raise ValueError(
            f"Definitions schema {version} is unsupported; expected {target}: {root}. "
            "Rerun installation maintenance."
        )
    changed = changed_paths(root)
    if changed:
        sample = ", ".join(map(str, changed[:5])) + (" ..." if len(changed) > 5 else "")
        raise ValueError(
            "Definitions changed outside nro's authoring commands: "
            f"{sample}. Restore the files or publish them with `nro definitions apply`."
        )


def changed_paths(root: Path) -> tuple[Path, ...]:
    """Return files whose current bytes differ from the recorded manifest."""
    root = Path(root)
    manifest = _read_manifest(root)
    if manifest is None:
        raise ValueError(f"Definitions store is unversioned: {root}")
    observed = _manifest_document(root, int(manifest["schema_version"]))["files"]
    recorded = manifest["files"]
    return tuple(
        Path(key)
        for key in sorted(set(observed) | set(recorded))
        if observed.get(key) != recorded.get(key)
    )


def normalize_managed_text(path: Path, text: str) -> str:
    """Add the management notice to comment-compatible definition formats."""
    if path.suffix.lower() not in {".yml", ".yaml", ".py"}:
        return text
    while text.startswith(MANAGED_NOTICE):
        text = text[len(MANAGED_NOTICE) :]
    lines = text.splitlines(keepends=True)
    if path.suffix.lower() == ".py" and lines and lines[0].startswith("#!"):
        body = "".join(lines[1:])
        while body.startswith(MANAGED_NOTICE):
            body = body[len(MANAGED_NOTICE) :]
        return lines[0] + MANAGED_NOTICE + body
    return MANAGED_NOTICE + text


def _adopt_unversioned(root: Path) -> None:
    for path in _managed_paths(root):
        if path.suffix.lower() in {".yml", ".yaml", ".py"}:
            text = path.read_text(encoding="utf-8")
            normalized = normalize_managed_text(path, text)
            if normalized != text:
                path.write_text(normalized, encoding="utf-8")


MIGRATIONS = (Migration(0, 1, "0.13.0", _adopt_unversioned),)
SCHEMA_VERSION = MIGRATIONS[-1].destination


def validate_migration_chain() -> None:
    """Require a continuous migration chain beginning at the legacy schema."""
    expected = 0
    for migration in MIGRATIONS:
        if migration.source != expected or migration.destination != expected + 1:
            raise RuntimeError("Definitions-store migrations must be consecutive")
        expected = migration.destination
    if expected != SCHEMA_VERSION:
        raise RuntimeError("Definitions-store migration target is inconsistent")


@contextmanager
def store_lock(root: Path) -> Iterator[None]:
    """Serialize migrations and CLI publication within one definitions store."""
    root = Path(root)
    root.mkdir(parents=True, exist_ok=True)
    descriptor = os.open(root / LOCK, os.O_CREAT | os.O_RDWR | os.O_NOFOLLOW, 0o664)
    with os.fdopen(descriptor, "a") as stream:
        fcntl.flock(stream, fcntl.LOCK_EX)
        _recover_interrupted_publication(root)
        yield


def _copy_store(source: Path, destination: Path) -> None:
    try:
        shutil.copytree(
            source,
            destination,
            symlinks=True,
            ignore=shutil.ignore_patterns(
                ".git",
                LOCK,
                RECOVERY,
                ".nro-incomplete",
                "*.swp",
                "*.swo",
                "*~",
                ".DS_Store",
                ".ipynb_checkpoints",
                "__pycache__",
            ),
        )
    except PermissionError as error:
        raise ValueError(
            f"Definitions contain a path that this installation cannot read: {error.filename}. "
            "Correct its ownership or permissions before maintenance."
        ) from error


def _atomic_bytes(path: Path, value: bytes, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    staged = path.with_name(f".{path.name}.tmp-{uuid.uuid4().hex}")
    try:
        with staged.open("wb") as stream:
            stream.write(value)
            stream.flush()
            os.fsync(stream.fileno())
        staged.chmod(mode)
        os.replace(staged, path)
        sync_directory(path.parent)
    finally:
        staged.unlink(missing_ok=True)


def _recovery_document(root: Path, relative_paths: set[Path]) -> dict[str, object]:
    entries: dict[str, object] = {}
    recovery = root / RECOVERY
    for relative in sorted(relative_paths):
        source = root / relative
        exists = source.is_file()
        mode = stat.S_IMODE(source.stat().st_mode) if exists else None
        entries[str(relative)] = {"exists": exists, "mode": mode}
        if exists:
            _atomic_bytes(recovery / "files" / relative, source.read_bytes(), mode)
    return {"state": "prepared", "files": entries}


def _read_recovery(root: Path) -> tuple[Path, dict[str, object]] | None:
    recovery = root / RECOVERY
    if not recovery.exists():
        return None
    if recovery.is_symlink() or not recovery.is_dir():
        raise ValueError(f"Invalid definitions recovery state: {recovery}")
    journal = recovery / "journal.yml"
    if not journal.is_file():
        # Publication begins only after the complete journal is durable. An
        # earlier interruption can therefore leave no modified definitions.
        shutil.rmtree(recovery)
        sync_directory(root)
        return None
    value = yaml.safe_load(journal.read_text(encoding="utf-8"))
    if (
        not isinstance(value, dict)
        or value.get("state") not in {"prepared", "committed"}
        or not isinstance(value.get("files"), dict)
    ):
        raise ValueError(f"Invalid definitions recovery journal: {journal}")
    return recovery, value


def _clear_recovery(root: Path, recovery: Path) -> None:
    shutil.rmtree(recovery)
    sync_directory(root)


def _recover_interrupted_publication(root: Path) -> None:
    state = _read_recovery(root)
    if state is None:
        return
    recovery, journal = state
    if journal["state"] == "committed":
        _clear_recovery(root, recovery)
        return
    for name, record in journal["files"].items():
        relative = Path(name)
        if relative.is_absolute() or ".." in relative.parts or not isinstance(record, dict):
            raise ValueError(f"Invalid definitions recovery entry: {name}")
        destination = root / relative
        if record.get("exists") is True and isinstance(record.get("mode"), int):
            source = recovery / "files" / relative
            if not source.is_file():
                raise ValueError(f"Missing definitions recovery copy: {source}")
            _atomic_bytes(destination, source.read_bytes(), record["mode"])
        elif record.get("exists") is False and record.get("mode") is None:
            destination.unlink(missing_ok=True)
        else:
            raise ValueError(f"Invalid definitions recovery entry: {name}")
    _clear_recovery(root, recovery)


def _begin_recovery(root: Path, relative_paths: set[Path]) -> Path:
    recovery = root / RECOVERY
    recovery.mkdir(mode=0o770)
    document = _recovery_document(root, relative_paths)
    atomic_write_text(
        recovery / "journal.yml",
        yaml.safe_dump(document, sort_keys=False),
        mode=0o660,
        durable=True,
    )
    sync_directory(root)
    return recovery


def _commit_recovery(root: Path, recovery: Path) -> None:
    journal = recovery / "journal.yml"
    document = yaml.safe_load(journal.read_text(encoding="utf-8"))
    document["state"] = "committed"
    atomic_write_text(
        journal,
        yaml.safe_dump(document, sort_keys=False),
        mode=0o660,
        durable=True,
    )
    _clear_recovery(root, recovery)


def _publish_staged(root: Path, staged: Path, *, relative_paths: set[Path] | None = None) -> None:
    if relative_paths is None:
        relative_paths = (
            {path.relative_to(staged) for path in _managed_paths(staged)}
            | {path.relative_to(root) for path in _managed_paths(root)}
            | {Path(MANIFEST)}
        )
    else:
        relative_paths = {Path(path) for path in relative_paths} | {Path(MANIFEST)}
    recovery = _begin_recovery(root, relative_paths)
    try:
        ordered = sorted(relative_paths - {Path(MANIFEST)}) + [Path(MANIFEST)]
        for relative in ordered:
            destination = root / relative
            source = staged / relative
            if not source.is_file():
                destination.unlink(missing_ok=True)
                continue
            mode = stat.S_IMODE(destination.stat().st_mode) if destination.is_file() else 0o664
            _atomic_bytes(destination, source.read_bytes(), mode)
        _commit_recovery(root, recovery)
    except Exception:
        _recover_interrupted_publication(root)
        raise


def migrate_store(
    root: Path,
    *,
    validate: Callable[[Path], None] | None = None,
) -> bool:
    """Migrate a store on a staged copy, then rewrite changed files in place."""
    root = Path(root).expanduser().resolve()
    validate_migration_chain()
    with store_lock(root):
        current = store_schema(root)
        if current > SCHEMA_VERSION:
            raise ValueError(
                f"Definitions schema {current} is newer than supported schema {SCHEMA_VERSION}"
            )
        if current == SCHEMA_VERSION:
            validate_store_integrity(root)
            if validate is not None:
                validate(root)
            return False
        with tempfile.TemporaryDirectory(prefix="nro-definitions-migration-") as temporary:
            staged = Path(temporary) / "store"
            _copy_store(root, staged)
            version = current
            for migration in MIGRATIONS:
                if migration.source == version:
                    migration.apply(staged)
                    version = migration.destination
            if version != SCHEMA_VERSION:
                raise ValueError(
                    f"No definitions migration path from schema {current} to {SCHEMA_VERSION}"
                )
            atomic_write_text(
                staged / MANIFEST,
                _manifest_text(staged, version),
                mode=0o664,
                durable=True,
            )
            validate_store_integrity(staged)
            if validate is not None:
                validate(staged)
            _publish_staged(root, staged)
        validate_store_integrity(root)
        return True


def refresh_manifest(root: Path) -> None:
    """Record one validated CLI transaction after its files are published."""
    root = Path(root).expanduser().resolve()
    version = store_schema(root)
    if version != SCHEMA_VERSION:
        raise ValueError("Definitions must be migrated before they can be edited")
    atomic_write_text(
        root / MANIFEST,
        _manifest_text(root, version),
        mode=0o664,
        durable=True,
    )


def update_store(
    root: Path,
    updates: dict[Path, bytes | None],
    *,
    validate: Callable[[Path], None] | None = None,
    adopt_drift: bool = False,
) -> None:
    """Validate and publish a CLI-authored multi-file transaction."""
    root = Path(root).expanduser().resolve()
    with store_lock(root):
        if adopt_drift:
            drift = set(changed_paths(root))
            omitted = drift - set(updates)
            if omitted:
                raise ValueError(
                    "The store has additional direct changes; include or restore them first: "
                    + ", ".join(map(str, sorted(omitted)))
                )
        else:
            validate_store_integrity(root)
        with tempfile.TemporaryDirectory(prefix="nro-definitions-update-") as temporary:
            staged = Path(temporary) / "store"
            _copy_store(root, staged)
            for relative, value in updates.items():
                relative = Path(relative)
                if relative.is_absolute() or ".." in relative.parts:
                    raise ValueError(f"Definition path must be relative: {relative}")
                if not relative.parts or relative.parts[0] not in MANAGED_CATEGORIES:
                    raise ValueError(f"Definition path is outside a managed category: {relative}")
                destination = staged / relative
                if value is None:
                    destination.unlink(missing_ok=False)
                    continue
                destination.parent.mkdir(parents=True, exist_ok=True)
                text = value.decode("utf-8")
                destination.write_text(normalize_managed_text(destination, text), encoding="utf-8")
            refresh_manifest(staged)
            validate_store_integrity(staged)
            if validate is not None:
                validate(staged)
            _publish_staged(root, staged, relative_paths=set(updates))
        validate_store_integrity(root)
