"""Compatibility imports for shared BIDS functional-reference resolution."""

from nro.engine.functional_references import (
    FmapPair,
    ImageRec,
    ReferenceInventory,
    ResolvedFuncReferences,
    ResolvedFuncRun,
    fmap_targets_bold,
    func_root_for_subject,
    infer_total_readout_time,
    inherit_sbref_metadata,
    load_rec,
    load_reference_inventory,
    nifti_shape3,
    opp_ped,
    pe_axis_and_sign,
    pick_nearest_opp_sbref,
    pick_prev_fmap_pair,
    pick_prev_sbref,
    read_nifti_shape_and_zooms,
    resolve_bold_from_run_stem,
    resolve_func_references,
    resolve_func_run_request,
    same_readout_time,
    same_voxel_sizes,
    voxel_sizes_3d,
)

__all__ = [
    "FmapPair",
    "ImageRec",
    "ReferenceInventory",
    "ResolvedFuncReferences",
    "ResolvedFuncRun",
    "fmap_targets_bold",
    "func_root_for_subject",
    "infer_total_readout_time",
    "inherit_sbref_metadata",
    "load_rec",
    "load_reference_inventory",
    "nifti_shape3",
    "opp_ped",
    "pe_axis_and_sign",
    "pick_nearest_opp_sbref",
    "pick_prev_fmap_pair",
    "pick_prev_sbref",
    "read_nifti_shape_and_zooms",
    "resolve_bold_from_run_stem",
    "resolve_func_references",
    "resolve_func_run_request",
    "same_readout_time",
    "same_voxel_sizes",
    "voxel_sizes_3d",
]
