"""Create, migrate, and edit protected site settings without moving data."""

import glob
import json
import os
import readline
import sys
from pathlib import Path

import yaml

from nro.configuration.site import (
    DERIVED,
    LAB,
    PATH_KEYS,
    generic_defaults,
    installation_record,
    read_overrides,
    read_site_definition,
    settings,
    site_definition_path,
    site_file,
    validate_setting,
    write_site_definition,
)
from nro.engine.io import atomic_write_text

DESCRIPTIONS = {
    "definitions": "Configurations, workflows, models, source markup, events, and ingestion profiles",
    "bids": "Directory containing BIDS projects",
    "work": "Intermediate files",
    "development": "Branch-owned derivatives, intermediate files, and debug BIDS",
    "registry": "Shared registry and logs",
    "images": "Container images",
    "gradient_coefficients": "Gradient-unwarping coefficient files",
    "templates": "TemplateFlow data",
    "workbench": "wb_command executable",
    "license": "Existing FreeSurfer license",
    "runtime": "Singularity or Apptainer executable",
    "oslom": "oslom_undir executable",
    "pycicada": "pycicada executable",
    "partition": "Slurm partition",
    "viewing_partition": "Slurm partition for interactive scene viewing",
    "account": "Slurm account (- for none)",
    "binds": "Container bind paths as a JSON list",
    "flywheel_server": "Default Flywheel server (- for none)",
    "flywheel_project": "Default Flywheel GROUP/PROJECT (- for none)",
}


def interactive_defaults(sources: dict) -> dict:
    """Suggest generic storage when lab storage is unavailable; retain explicit settings."""
    if LAB.is_dir() and os.access(LAB, os.R_OK | os.X_OK):
        return {}
    return {
        key: value for key, value in generic_defaults().items() if sources[key] == "lab default"
    }


def save_settings(path: Path, overrides: dict) -> Path:
    """Save protected settings in definitions and retain only its locator in TOML."""
    for key, value in overrides.items():
        validate_setting(key, value)
    existing = read_overrides(path)
    definitions = (
        Path(
            overrides.get(
                "definitions", existing.get("definitions", settings(path=path)[0]["definitions"])
            )
        )
        .expanduser()
        .resolve()
    )
    protected_path = site_definition_path(definitions)
    if protected_path.is_file() and "definitions" in (set(existing) | set(overrides)):
        current, bidsify = read_site_definition(definitions)
        current.update({key: value for key, value in overrides.items() if key != "definitions"})
        flywheel_server = current.pop("flywheel_server", None)
        flywheel_project = current.pop("flywheel_project", None)
        if flywheel_server is not None:
            bidsify["default_server"] = flywheel_server or None
        if flywheel_project is not None:
            bidsify["default_project"] = flywheel_project or None
        write_site_definition(definitions, current, bidsify=bidsify)
        _write_locator(path, definitions)
        return protected_path
    # First installation must retain the proposed values long enough to create
    # its definitions store. Setup migrates this temporary legacy form before
    # publishing a ready installation.
    text = "# Temporary nro setup settings; installation moves these into definitions.\n"
    text += "".join(f"{key} = {json.dumps(value)}\n" for key, value in sorted(overrides.items()))
    atomic_write_text(path, text, mode=0o644, durable=True)
    return path


def _write_locator(path: Path, definitions: Path) -> None:
    """Replace the disposable installation file with one definitions pointer."""
    text = "# Generated by nro; rerun ./install to recreate this locator.\n"
    text += f"definitions = {json.dumps(str(definitions))}\n"
    atomic_write_text(path, text, mode=0o644, durable=True)


def migrate_site_configuration(path: Path) -> Path:
    """Move legacy deployment and source-system settings into definitions.

    The definitions document and reduced bidsification profile are published
    before the locator changes. An interrupted migration therefore remains
    readable and can be repeated.
    """
    path = Path(path)
    values, _ = settings(path=path)
    definitions = Path(values["definitions"]).expanduser().resolve()
    protected_path = site_definition_path(definitions)
    if protected_path.is_file():
        protected, bidsify = read_site_definition(definitions)
        legacy = read_overrides(path)
        resolved = dict(protected)
        for key, (parent, suffix) in DERIVED.items():
            resolved.setdefault(key, str(Path(resolved[parent]) / suffix))
        resolved["flywheel_server"] = bidsify["default_server"] or ""
        resolved["flywheel_project"] = bidsify["default_project"] or ""
        conflicts = [
            key
            for key, value in legacy.items()
            if key != "definitions" and resolved.get(key) != value
        ]
        if conflicts:
            raise ValueError(
                "Legacy site settings differ from site/site.yml: " + ", ".join(sorted(conflicts))
            )
    else:
        protected = {
            key: value
            for key, value in values.items()
            if key not in {"definitions", "flywheel_server", "flywheel_project"}
        }
        bidsify = {
            "default_server": values.get("flywheel_server") or None,
            "default_project": values.get("flywheel_project") or None,
        }
    migrated_profiles = {}
    for profile_path in sorted((definitions / "bidsify").glob("*.yml")):
        profile = yaml.safe_load(profile_path.read_text(encoding="utf-8")) or {}
        if not isinstance(profile, dict):
            raise ValueError(f"Invalid bidsification profile: {profile_path}")
        changed = False
        for key in ("servers", "project_sources", "session_rules", "event_rules"):
            if key in profile:
                candidate = profile.pop(key)
                changed = True
                current = bidsify.get(key)
                if (
                    candidate not in (None, {}, [])
                    and current not in (None, {}, [])
                    and current != candidate
                ):
                    raise ValueError(f"Protected bidsification setting differs: {key}")
                if candidate not in (None, {}, []):
                    bidsify[key] = candidate
        scanplans = profile.get("scanplans")
        if isinstance(scanplans, dict):
            protected_scanplans = dict(bidsify.get("scanplans") or {})
            for key in ("location", "credential_env"):
                if key in scanplans:
                    candidate = scanplans.pop(key)
                    changed = True
                    current = protected_scanplans.get(key)
                    if candidate is not None and current is not None and current != candidate:
                        raise ValueError(f"Protected scan-plan setting differs: {key}")
                    if candidate is not None:
                        protected_scanplans[key] = candidate
            bidsify["scanplans"] = protected_scanplans
        if changed:
            migrated_profiles[profile_path] = profile
    write_site_definition(definitions, protected, bidsify=bidsify)
    for profile_path, profile in migrated_profiles.items():
        atomic_write_text(
            profile_path,
            yaml.safe_dump(profile, sort_keys=False),
            mode=0o644,
            durable=True,
        )
    _write_locator(path, definitions)
    return protected_path


def edit_settings(assignments=None, *, maintain=False, path=None) -> None:
    """Edit independent site values interactively or from key=value assignments.

    Shared edits require maintenance authorization and an inactive worker pool.
    Cancellation before save leaves the old file intact. No data are relocated.
    """
    if installation_record().get("mode") == "branch":
        raise ValueError(
            "Branch installations cannot edit the shared site; use its maintainer installation"
        )
    if installation_record().get("mode") == "shared" and not maintain:
        raise ValueError("Shared settings require --maintain and maintainer write access.")
    path = site_file() if path is None else path
    if installation_record().get("mode") == "shared":
        from nro.engine.bootstrap import check_workers

        check_workers(path)
    overrides = read_overrides(path)
    values, sources = settings(path=path)
    if assignments:
        for assignment in assignments:
            key, separator, value = assignment.partition("=")
            if not separator:
                raise ValueError(f"Expected key=value: {assignment!r}")
            if key == "binds":
                value = json.loads(value)
            elif key in PATH_KEYS:
                value = str(Path(value).expanduser())
            validate_setting(key, value)
            overrides[key] = value
    else:
        if not sys.stdin.isatty():
            raise ValueError("Interactive setup needs a terminal; use paths set key=value.")

        def complete(text, state):
            matches = glob.glob(os.path.expanduser(text) + "*")
            return matches[state] if state < len(matches) else None

        previous = readline.get_completer()
        readline.set_completer(complete)
        readline.parse_and_bind("tab: complete")
        try:
            proposals = interactive_defaults(sources)
            values.update(proposals)
            if "binds" in proposals:
                overrides["binds"] = proposals["binds"]
            print(f"Site configuration: {path}\nEnter keeps a value; Tab completes paths.")
            print("Proposed settings:")
            for key in DESCRIPTIONS:
                print(f"  {key}: {values[key]}")
            accept_all = input("Accept all defaults? [Y/n]: ").strip().lower() in {"", "y", "yes"}
            for key, description in DESCRIPTIONS.items():
                entered = (
                    "" if accept_all else input(f"{description}\n  {key} [{values[key]}]: ").strip()
                )
                value = entered or values[key]
                if key == "binds" and entered:
                    value = json.loads(entered)
                if key in {"account", "flywheel_server", "flywheel_project"} and entered == "-":
                    value = ""
                if key in PATH_KEYS:
                    value = str(Path(value).expanduser())
                validate_setting(key, value)
                overrides[key] = value
            for key, value in sorted(overrides.items()):
                print(f"  {key} = {value}")
            if input("Save? [Y/n]: ").strip().lower() not in {"", "y", "yes"}:
                return
        finally:
            readline.set_completer(previous)
    destination = save_settings(path, overrides)
    print(f"Saved {destination}. New commands use these settings; existing data were not moved.")
